export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      ['feat', 'fix', 'docs', 'style', 'refactor', 'perf', 'test', 'build', 'ci', 'chore', 'revert'],
    ],
    'scope-enum': [
      2,
      'always',
      [
        'admin',
        'api',
        'auth',
        'checkout',
        'chat',
        'email',
        'home',
        'inventory',
        'orders',
        'products',
        'profile',
        'reviews',
        'scripts',
        'services',
        'supabase',
        'tooling',
        'deps',
      ],
    ],
    'scope-case': [2, 'always', 'kebab-case'],
    'subject-case': [2, 'never', ['sentence-case', 'start-case', 'pascal-case', 'upper-case']],
  },
};
